version: '3.5'
services:
    Earnapp:
        image: fazalfarhan01/earnapp:lite
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - earnapp-data:/etc/earnapp
        environment: 
            EARNAPP_UUID: $EARNAPP_UUID
        privileged: true
        restart: always
        network_mode: host
    IproyalPawns:
        image: iproyal/pawns-cli
        command: -email=$IPROYALPAWNS_EMAIL -password='$IPROYALPAWNS_PASSWD' -device-name=$DEVICE_NAME -accept-tos
        restart: always
        network_mode: host
    Peer2profit:
        image: peer2profit/peer2profit_linux
        restart: always
        network_mode: host
        environment:
            - P2P_EMAIL=$IPROYALPAWNS_EMAIL
    Honeygain:
        image: honeygain/honeygain
        platform: linux/amd64
        command: -tou-accept -email $IPROYALPAWNS_EMAIL -pass $IPROYALPAWNS_PASSWD -device $DEVICE_NAME
        restart: always
        network_mode: host
    Repocket:
        image: repocket/repocket:latest
        restart: always
        network_mode: host
        environment:
          - RP_EMAIL=$IPROYALPAWNS_EMAIL
          - RP_API_KEY=$RP_API_KEY
    TraffMonetizer:
        container_name: traffmonetizer
        image: traffmonetizer/cli:latest
        environment:
          - TRAFFMONETIZER_DUMMY=''
        command: start accept status --token $TM_TOKEN --device-name $DEVICE_NAME
        restart: always
        network_mode: host
volumes:
    portainer_data:
    earnapp-data:
